version: 2
formats: []

build:
  image: latest
  jobs:
    post_install:
      - pip install git+https://github.com/Rapptz/discord.py.git@master # Unfortunate

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs