name: build

on:
  push:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  dists-and-docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8' ]

    name: dists & docs
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel git+https://github.com/rapptz/discord.py.git@master
          pip install -U -r requirements.txt
      - name: Build distributions
        run: |
          python ./setup.py sdist bdist_wheel
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: distributions
      #     path: dist/*

      - name: Install package
        run: |
          pip install -e .[docs]
      - name: Build docs
        shell: bash
        run: |
          cd docs
          sphinx-build -b html -D language=en -a -n -T -W --keep-going . _build/html
        env:
          DOCS_LANGUAGE: en

      # - name: Upload docs
      #   uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: docs-en
      #     path: docs/_build/html/*